spring:
  profiles:
    include: google, kakao, naver

---
spring:
  profiles: google
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: 446656770248-b1nbil37bvj97f8j4b4kpc64o2rtbpag.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
---
spring:
  profiles: kakao
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: 4353a4e1b169a1005f992567e3355384
            client-secret: u2u25enzyMcXyhTHP5hmPlFk5PUqI6eA
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - profile_nickname
              - profile_image
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            user-info-uri: https://kapi.kakao.com/v2/user/me
            token-uri: https://kauth.kakao.com/oauth/token
            user-name-attribute: id
---
spring:
  profiles: naver
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: zbyW5YnU7K4M6IRJrQf5
            client-secret: 3hk1UzIs81
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - email
              - name
              - profile_image
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token
            user-name-attribute: response